name = "astral-notes"
main = "dist/server/server.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"

[[d1_databases]]
binding = "DB"
database_name = "astral-notes"
database_id = "fec259fe-584e-4b4f-89a3-dd075a4c5472"
