/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as ApiPublicDbActionRouteImport } from './routes/api/public/db/$action'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDbActionRoute = ApiPublicDbActionRouteImport.update({
  id: '/api/public/db/$action',
  path: '/api/public/db/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/$id': typeof SIdRoute
  '/api/public/db/$action': typeof ApiPublicDbActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$id': typeof SIdRoute
  '/api/public/db/$action': typeof ApiPublicDbActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s/$id': typeof SIdRoute
  '/api/public/db/$action': typeof ApiPublicDbActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/s/$id' | '/api/public/db/$action'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/$id' | '/api/public/db/$action'
  id: '__root__' | '/' | '/s/$id' | '/api/public/db/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SIdRoute: typeof SIdRoute
  ApiPublicDbActionRoute: typeof ApiPublicDbActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/db/$action': {
      id: '/api/public/db/$action'
      path: '/api/public/db/$action'
      fullPath: '/api/public/db/$action'
      preLoaderRoute: typeof ApiPublicDbActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SIdRoute: SIdRoute,
  ApiPublicDbActionRoute: ApiPublicDbActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
